version: "3.8"

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parashare-homepage-website-1
    ports:
      - "127.0.0.1:3000:4173"
    restart: unless-stopped